# Generated by Django 3.1.4 on 2020-12-13 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="client",
        ),
        migrations.RemoveField(
            model_name="suggestion",
            name="client",
        ),
        migrations.RemoveField(
            model_name="vote",
            name="client",
        ),
        migrations.DeleteModel(
            name="Client",
        ),
    ]
