# Generated by Django 3.1.4 on 2020-12-10 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_client_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='posts.client'),
        ),
    ]
