# Generated by Django 3.1.4 on 2021-01-01 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20201213_0614'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuggestionApproval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved_at', models.DateTimeField()),
                ('suggestion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='posts.suggestion')),
            ],
        ),
        migrations.CreateModel(
            name='PostApproval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved_at', models.DateTimeField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='posts.post')),
            ],
        ),
    ]
