# Generated by Django 3.1.4 on 2021-01-01 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_postapproval_suggestionapproval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postapproval',
            name='approved_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='suggestionapproval',
            name='approved_at',
            field=models.DateTimeField(null=True),
        ),
    ]
